### ISSUE TITLE
Printable version

### ISSUE THREAD

**Issue by alberduris** [omarsar/nlp_overview#6]
This repo is a great work!

The current version is almost impossible to print with a decent quality. 

If Ctrl+P from the HTML version the output PDF gets messed up.

Is it possible to have a decent printable version? Is it planned?

Thanks!

**Comment by omarsar** [comment]
Hi! You can check out the PDF format here: https://arxiv.org/abs/1708.02709. We borrow most of the content from this paper. 
The web version is for those that prefer it in this version and for also encouraging others to submit improvements due to the fast pace of NLP research. Thank you! Enjoy!

**Comment by alberduris** [comment]
That's perfect! Thank you very much 👍
